# Generated by Django 4.2.7 on 2024-05-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0002_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='documento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('1', 'OK'), ('0', 'Cancelado')], default='1', max_length=1, verbose_name='OK'),
        ),
    ]
