# FROM python:3.8
# ENV PYTHONUNBUFFERED=1
# WORKDIR /code

# #COPY requirements.txt /code
# COPY pyproject.toml poetry.lock /app/ 


# RUN pip -mpip install --upgrade pip 
# RUN pip install poetry
# RUN poetry config virtualenvs.create false
# RUN poetry install --no-dev


# COPY . /code/

# EXPOSE 8000

# CMD ["poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"] 